[package]
name = "rough-image"
version = "0.1.0"
authors = ["kmkzt <info.pscreator@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22"
num-complex = "0.2.3"
gif = "0.10.2"
